resolver: lts-20.5
compiler: ghc-9.2.5
allow-newer: true
system-ghc: true

packages:
    - .
    - ../common/etna-lib

extra-include-dirs:
    - /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/ffi
